### PR TITLE
Ntd1hc/feat/robfw 357/alignment of names for 2db tools

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi Thomas,

The package name and app name has been renamed and updated in sources accordingly.
The repository name and its links have been updated in README and document files, too.

Please help to rename this repository as `robotframework-robotlog2rqm` to align with changes in this pull request.

Thank you,
Ngoan

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Configuration of repo and GenPackageDoc works properly. Please check the deletion of the folder with old name: RobotResults2RQM. After cloning I have both RobotResults2RQM and RobotLog2RQM.

**Comment by ngoan1608** [comment]
> Configuration of repo and GenPackageDoc works properly. Please check the deletion of the folder with old name: RobotResults2RQM. After cloning I have both RobotResults2RQM and RobotLog2RQM.

Hi Holger,

I have renamed that folder and that action has been reflected in the [Files changed](https://github.com/test-fullautomation/robotframework-robotlog2rqm/pull/19/files) tab.
Could you please double check this issue?

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

this is so much tricky. Because of your latest pull request is not yet merged, I worked with both the develop branch and your feature branch containing your latest changes - but in the same folder. That's the reason for having two package folders. All things fine now. ;-)

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,

puh, what a mass of consequences. But better to change now than later...

Thank you,
 Thomas

**Pull request merged**
