### PR TITLE
Ntd1hc/feat/maintain document with genpackagedoc

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi @ThPoll ,
Hi @HolQue ,

Please review the document, docstring updates due to new genpackage doc tool.

Thank you,
Ngoan

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi Holger,

First: The generated documents looks very impressive for me.

Nevertheless I have some findings. Please comment it:
1. page 4:
grafik
How to make the box fitting?
2. page 4
grafik
Class is then RobotResults2RQM.CRQM.CRQMClient? (I did not check the sources), but this would be my understanding?
3. page 10:
grafik
NewLine indicator only left side, right-side missing. Would expect two for consistency.
Thank you, 
 Thomas

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,
looks very good to me!
@HolQue : Please answer my comment.
Thank you,
 Thomas

**Comment by HolQue** [comment]
1. Needs deeper analysis (in progress).
2. The textbox with grey background color contains the path to the Python file (RobotResults2RQM\CRQM.py). The "Class" in headline is the name of the class like defined within this Python file.
3. Here we are inside a docstring (and not inside the manually maintained LaTeX code). The LaTeX code is generated by Pandoc (out of the rst code inside the doctrings). And this happens under Pandoc conditions. This is not aligned with the style we use in our own LaTeX code. To realize such a alignment would require to hijack the Pandoc source code - and this is currently not in focus. This means we have to live with these style differences.

**Comment by HolQue** [comment]
The version in file version.py (1.1.1) does not fit to the version indicated in the history (0.2.0). But both should be aligned.

**Review by HolQue — COMMENTED** [review]
The version in file version.py (1.1.1) does not fit to the version indicated in the history (0.2.0). But both should be aligned.

**Comment by HolQue** [comment]
Please use \begin/end{robotcode} instead of \rcode in case of the code exceeds the width of the table column.

**Comment by HolQue** [comment]
The table mentioned above now also exceeds the height of a DIN A 4 page in PDF output.

Please use the `longtable `environment of LaTeX for long tables instead of the `table `environment.

**Comment by ngoan1608** [comment]
> The table mentioned above now also exceeds the height of a DIN A 4 page in PDF output.
> 
> Please use the `longtable `environment of LaTeX for long tables instead of the `table `environment.

Hi @HolQue ,

I do not use `longtable` because I want it to be displayed in the single page.
I have adapt the table to make the height fit to the page.

Thank you,
Ngoan

**Review by test-fullautomation — APPROVED** [review]
Hi both,
looks super now!
Nice (also a bit complex) sample for the team!

Thank you,
Thomas

**Comment by HolQue** [comment]
Added full explanation:
[LaTeXTable.pdf](https://github.com/test-fullautomation/robotframework-testresult2rqmtool/files/9422439/LaTeXTable.pdf)

**Pull request merged**
